import { describe, expect, it } from 'vitest'
import { createRegex } from '../src/handler'

describe('regex', () => {
  const regex = createRegex('test-me', '0.0.1', '0.0.2')

  it('conf should work', () => {
    const conf = `
{
  "productName": "test-me",
  "version": "0.0.1",
  "build": {
    "beforeDevCommand": "pnpm dev",
  },
}
`

    expect(regex.conf(conf)).toMatchInlineSnapshot(`
      "
      {
        "productName": "test-me",
        "version": "0.0.2",
        "build": {
          "beforeDevCommand": "pnpm dev",
        },
      }
      "
    `)
  })

  it('toml should work', () => {
    const toml = `
[package]
name = "test-me"
version = "0.0.1"
[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
`

    expect(regex.toml(toml)).toMatchInlineSnapshot(`
      "
      [package]
      name = "test-me"
      version = "0.0.2"
      [lib]
      name = "app_lib"
      crate-type = ["staticlib", "cdylib", "rlib"]

      [build-dependencies]
      tauri-build = { version = "2.4.1", features = [] }

      [dependencies]
      serde_json = "1.0"
      serde = { version = "1.0", features = ["derive"] }

      [profile.release]
      codegen-units = 1 # Allows LLVM to perform better optimization.
      lto = true # Enables link-time-optimizations.
      "
    `)
  })

  it('lock should work', () => {
    const lock = `
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "adler2"
version = "2.0.1"

[[package]]
name = "test-me"
version = "0.0.1"

[[package]]
name = "aho-corasick"
version = "1.1.3"
dependencies = [
 "memchr",
]
`

    expect(regex.lock(lock)).toMatchInlineSnapshot(`
      "
      # This file is automatically @generated by Cargo.
      # It is not intended for manual editing.
      version = 3

      [[package]]
      name = "adler2"
      version = "2.0.1"

      [[package]]
      name = "test-me"
      version = "0.0.2"

      [[package]]
      name = "aho-corasick"
      version = "1.1.3"
      dependencies = [
       "memchr",
      ]
      "
    `)
  })
})
